- name: Install internal monitoring
  include_tasks: install.yml
  when: kind is undefined or kind == "install"

- name: Remove internal monitoring
  include_tasks: remove.yml
  when: kind is defined and kind == "uninstall"