- name: Apply namespace
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'namespace.j2') }}"
    state: absent
    kubeconfig: "{{ kubeconfig_file_location }}"

- name: Service account
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'service-account.j2') }}"
    state: absent
    kubeconfig: "{{ kubeconfig_file_location }}"

- name: Service account secret
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'secret.j2') }}"
    state: absent
    kubeconfig: "{{ kubeconfig_file_location }}"

- name: Retrieve token
  ansible.builtin.command: "kubectl get secret {{namespace_name}}-token -n {{namespace_name}} -o jsonpath='{.data.token}'"
  register: token_output

- name: Set bearer token fact
  ansible.builtin.set_fact:
    bearer_token: "{{ token_output.stdout }}"

- name: Cluster role
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'cluster-role.j2') }}"
    state: absent
    kubeconfig: "{{ kubeconfig_file_location }}"

- name: Cluster role binding
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'cr-binding.j2') }}"
    state: absent
    kubeconfig: "{{ kubeconfig_file_location }}"

- name: Config map
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'configmap.j2') }}"
    state: absent
    kubeconfig: "{{ kubeconfig_file_location }}"

- name: Deployment
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'daemonset.j2') }}"
    state: absent
    kubeconfig: "{{ kubeconfig_file_location }}"