---
- hosts: all
  become: True

  pre_tasks:
    - name: Check if k3s is already installed
      ansible.builtin.command: "k3s --version"
      register: k3s_exists
      ignore_errors: true

    - name: Stdout K3s --version"
      ansible.builtin.debug:
        var: k3s_exists.stdout
      when: k3s_exists.stdout is defined

  roles:
    - role: install_k3s
      when: k3s_exists.rc != 0
