apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.alloy.volume.config.configMap }}
  labels:
    app: {{ .Values.alloy.name }}
data:
  config.alloy: |
    {{ .Values.alloy_config | nindent 4 }}