- name: Add Rabbitmq Operator repository
  kubernetes.core.helm_repository:
    name: bitnami
    repo_url: https://charts.bitnami.com/bitnami

- name: Install Rabbitmq Operator via Helm
  kubernetes.core.helm:
    kubeconfig: "{{ kubeconfig_file_location }}"
    name: rabbitmq-cluster-operator
    chart_ref: bitnami/rabbitmq-cluster-operator
    release_namespace: rabbitmq-system
    create_namespace: true
    state: present

- name: Install RabbitMQ topology operator
  ansible.builtin.shell: |
    kubectl apply -f https://github.com/rabbitmq/messaging-topology-operator/releases/latest/download/messaging-topology-operator-with-certmanager.yaml