- name: Install cert manager
  ansible.builtin.shell: |
    kubectl delete -f https://github.com/cert-manager/cert-manager/releases/download/v1.17.0/cert-manager.yaml

- name: Retrieve installation status
  ansible.builtin.shell: |
    kubectl get pods --namespace cert-manager
  register: cert_manager_pods

- name: Debug installation status
  ansible.builtin.debug:
    var: cert_manager_pods.stdout_lines