# Install Docker on different Linux distributions
# -------------------------------------------
# This playbook installs Docker on different Linux distributions.
# The playbook uses the when conditional statement to install Docker on Ubuntu, Debian, and Rocky Linux.
# -------------------------------------------
# The playbook includes the tasks for each distribution in separate files.
# The playbook also includes a notify directive to start the Docker service after installation.
# The playbook uses the ansible_distribution variable to get the distribution of the target host.
# The playbook uses the ansible.builtin.debug module to display the distribution of the target host.
---
- name: Get distro
  ansible.builtin.debug:
    var: ansible_distribution

- name: Install Docker on Ubuntu
  include_tasks: debian.yml
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

- name: Install Docker on Rocky
  include_tasks: rocky.yml
  when: ansible_distribution == 'Rocky' or ansible_distribution == 'RedHat'
