---
- name: Debug os
  ansible.builtin.debug:
    var: ansible_distribution

- name: Ensure ssh folder exists
  ansible.builtin.file:
    path: ~/.ssh
    state: directory

- name: Ensure ssh_key_filename_identifier is a string
  ansible.builtin.set_fact:
    ssh_key_filename_identifier: "{{ ssh_key_filename_identifier | default('') | string if ssh_key_filename_identifier | default('') | string != 'None' else '' }}"

- name: Compute suffix for ssh key filename
  ansible.builtin.set_fact:
    ssh_key_suffix: "{{ ('_' + ssh_key_filename_identifier) if ssh_key_filename_identifier | length > 0 else '' }}"

- name: Generate SSH keys with identifier
  ansible.builtin.openssh_keypair:
    comment: "{{ ssh_key_comment }}"
    path: "~/.ssh/{{ private_key_filename }}{{ ssh_key_suffix }}"
    type: "ed25519"
    state: present
    passphrase: "{{ ssh_passphrase }}"
  register: ssh_key

- name: Debug SSH keys path
  ansible.builtin.debug:
    var: ssh_key.filename

- name: Debug SSH keys value
  ansible.builtin.debug:
    var: ssh_key.public_key
  failed_when: ssh_key.public_key is not defined
