---
- hosts: k8s_master
  become: true
  gather_facts: false

  roles:
    - role: kafka_install
      when: install_kafka is defined and install_kafka | bool == true

    - role: kafka_cluster
    - role: kafka_create_user
    - role: kafka_topic
