---
- hosts: k8s_master
  become: true
  gather_facts: false

  roles:
    - role: kafka_install
      when: install_kafka is defined and install_kafka | bool == true

    - role: kafka_cluster
    - role: kafka_create_user
    - role: kafka_topic

  tasks:
    - name: Get user name
      ansible.builtin.debug:
        var: kafka_user_credentials.username

    - name: Get user password
      ansible.builtin.debug:
        var: kafka_user_credentials.password