---
- hosts: k8s_master
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become: true
  gather_facts: false

  pre_tasks:
    - name: Install python3-kubernetes
      become: true
      ansible.builtin.package:
        name: python3-kubernetes
        state: present

  roles:
    - role: k8s_user
