tls:
  cert_manager:
    issuer: letsencrypt-issuer

pyroscope:
  name: pyroscope
  kind: StatefulSet
  replicas: 1
  specs:
    container_name: pyroscope
    image: grafana/pyroscope:1.14.0
    container_port: 4040
    exposed_port: 4040
  hpa:
    min: 1
    max: 1
    cpu: 120
    memory: 120