---
- hosts: localhost
  connection: local
  become: false
  gather_facts: false
  environment: 
    K8S_AUTH_KUBECONFIG: ".kube/kubeconfig.yml"
  vars:
    namespace: robsgbl0
    tls:
      cert_manager:
        issuer: letsencrypt-issuer
  pre_tasks:
    - name: Python kubernetes install
      ansible.builtin.pip:
        name: kubernetes
        executable: pip3

  roles:
    - role: alloy
    - role: mimir
    - role: loki
    - role: tempo
    - role: pyroscope
    - role: grafana