---
- hosts: localhost
  connection: local
  become: false
  gather_facts: false
  environment: 
    K8S_AUTH_SSL_CA_CERT: "cert/ca.crt"
    K8S_AUTH_HOST: "{{ k8s_host }}"
    K8S_AUTH_API_KEY: "{{ k8s_token }}"
  vars:
    namespace: robsgbl0
    tls:
      cert_manager:
        issuer: letsencrypt-issuer
  pre_tasks:
    - name: Python kubernetes install
      ansible.builtin.pip:
        name: kubernetes
        executable: pip3

  roles:
    - role: alloy
    - role: mimir
    - role: loki
    - role: tempo
    - role: pyroscope
    - role: grafana