---
- name: Cleanup old install
  ansible.builtin.command: "for pkg in docker.io docker-doc docker-compose podman-docker containerd runc; do sudo apt-get remove $pkg; done"
  ignore_errors: true

- name: Install prerequisites
  ansible.builtin.package:
    pkg:
      - ca-certificates
      - curl
    state: latest

- name: Install keyring
  ansible.builtin.command: "install -m 0755 -d /etc/apt/keyrings"

- name: Download the docker package
  ansible.builtin.uri:
    url: "{{ docker_package_url_ubuntu }}"
    dest: "/etc/apt/keyrings/docker.asc"
    mode: "0755"
  register: docker_gpg_result_ubuntu
  ignore_errors: true
  when: ansible_distribution == 'Ubuntu'

- name: Download the docker package
  ansible.builtin.uri:
    url: "{{ docker_package_url_debian }}"
    dest: "/etc/apt/keyrings/docker.asc"
    mode: "0755"
  register: docker_gpg_result_debian
  ignore_errors: true
  when: ansible_distribution == 'Debian'

- name: Check if the download was successful for Ubuntu
  ansible.builtin.fail:
    msg: "Failed to download the docker gpg key for Ubuntu"
  when: ansible_distribution == 'Ubuntu' and docker_gpg_result_ubuntu.status != 200 and docker_gpg_result_ubuntu.status != 304

- name: Check if the download was successful for Debian
  ansible.builtin.fail:
    msg: "Failed to download the docker gpg key for Debian"
  when: ansible_distribution == 'Debian' and docker_gpg_result_debian.status != 200 and docker_gpg_result_debian.status != 304

- name: Changing permissions
  ansible.builtin.file:
    path: "/etc/apt/keyrings/docker.asc"
    mode: "a+r"

- name: Add the docker repository
  ansible.builtin.shell: |
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] {{ registry_docker_debian }} \
    $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
    sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  when: ansible_distribution == 'Debian'

- name: Add the docker repository
  ansible.builtin.shell: |
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] {{ registry_docker_ubuntu }} \
    $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}") stable" | \
    sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  when: ansible_distribution == 'Ubuntu'

- name: Update Apt with the docker registry
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 0 # force the update

- name: Install docker packages
  ansible.builtin.package:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest

- name: Test installation
  ansible.builtin.command: "docker --version"
  register: docker_version

- debug:
    msg: "{{ docker_version.stdout }}"
  failed_when: docker_version.rc != 0
  notify: Start dockerd
