multitenancy_enabled: false

usage_report:
  reporting_enabled: false

compactor:
  compaction:
    block_retention: 24h

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: "0.0.0.0:4317"
        http:
          endpoint: "0.0.0.0:4318"

ingester:
  flush_check_period: 10s
  trace_idle_period: 10s
  max_block_duration: 30m
  complete_block_timeout: 1h

server:
  http_listen_port: 3100
  grpc_listen_port: 3200
  log_level: info

storage:
  trace:
    backend: local
    local:
      path: /var/tempo/traces
    wal:
      path: /var/tempo/wal

querier:
  max_concurrent_queries: 20

query_frontend:
  search:
    concurrent_jobs: 2000

overrides:
  defaults:
    metrics_generator:
      processors:
        - service-graphs
        - span-metrics
  per_tenant_override_config: /conf/overrides.yaml

metrics_generator:
  storage:
    path: "/tmp/tempo"
    remote_write:
      - url: "http://mimir-service:9002/api/v1/write"
