grafana:
  name: grafana
  kind: Deployment
  secret_name: grafana-secret
  secrets:
    db_url: ""
  specs:
    replicas: 1
    container_name: grafana
    image: grafana/grafana:12.0.2
    container_port: 3000
    exposed_port: 3000
  volume:
    name: grafana-pvc
    storage: 1Gi
  ingress:
    host: grafana.neryolab.com
  hpa:
    min: 1
    max: 1
    cpu: 120
    memory: 120

grafana_provisioning:
  name: grafana-provisioning
  volume:
    config:
      name: grafana-provisioning-conf
      configMap: grafana-provisioning-config
      path: /etc/grafana/provisioning/datasources/datasources.yaml
      subPath: datasources.yaml