# Description: Add the ssh key to the user's authorized_keys file
# Prerequisites: The user must be created
# The ssh key must be generated
# The ssh key must be stored in a vault and placed in the group_vars folder as "ssh_public_key"
---
- name: Must use vault to send key to the client
  fail:
    msg: "use_vault must be set to true"
  when: not use_vault

- name: Check if user is defined
  fail:
    msg: "user is not defined"
  when: user is not defined

- name: Check if ssh_public_key is defined
  fail:
    msg: "ssh_public_key is not defined"
  when: ssh_public_key is not defined

- name: Check if ssh folder exists
  become: true
  ansible.builtin.file:
    path: "/home/{{ user }}/.ssh"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0700"

- name: Add the public key
  become: true
  ansible.builtin.copy:
    content: "{{ ssh_public_key }}"
    dest: "/home/{{ user }}/.ssh/authorized_keys"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0600"
  notify:
    - Restart ssh service - docker
    - Restart ssh service - server

- name: Check the content of authorized_keys
  ansible.builtin.shell: "cat /home/{{ user }}/.ssh/authorized_keys"
  register: ssh_key_check

- name: Debug authorized_keys
  ansible.builtin.debug:
    var: ssh_key_check.stdout
