tempo:
  name: tempo
  kind: StatefulSet
  specs:
    replicas: 1
    container_name: tempo
    image: grafana/tempo:2.8.1
    ports:
      - port: 3100
        protocol: TCP
        exposed_port: 3100
        name: http
      - port: 4317
        protocol: TCP
        exposed_port: 4317
        name: grpc
  volume:
    config:
      name: tempo-config
      configMap: tempo-config
      path: /etc/tempo.yaml
      subPath: tempo.yaml
  hpa:
    min: 1
    max: 1
    cpu: 120
    memory: 120