---
- name: Uninstall k3s server
  ansible.builtin.shell:
    cmd: k3s-uninstall.sh
    chdir: /usr/local/bin/

- name: Check uninstall
  ansible.builtin.command: "k3s --version"
  register: k3s_version
  ignore_errors: true

- name: Print k3s version
  ansible.builtin.debug:
    msg: "{{ k3s_version.stdout }}"
  failed_when: k3s_version.rc == 0
