apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.loki.volume.config.configMap }}
  labels:
    app: {{ .Values.loki.name }}
data:
  loki.yaml: |
    {{ .Values.loki_config | nindent 4 }}