---
- name: Apply node-pool
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'node-pool.j2') }}"
    namespace: "{{ k8s_namespace }}"
    state: present
    kubeconfig: "{{ kubeconfig_file_location }}"

- name: Apply cluster configuration
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'cluster.j2') }}"
    namespace: "{{ k8s_namespace }}"
    state: present
    kubeconfig: "{{ kubeconfig_file_location }}"