- name: Add Rabbitmq cluster
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'cluster.j2') }}"
    namespace: "{{ k8s_namespace }}"
    state: present
    kubeconfig: "{{ kubeconfig_file_location }}"