- name: Install cert manager
  include_tasks: install.yml
  when: kind is not defined or kind != "delete"

- name: Uninstall cert manager
  include_tasks: delete.yml
  when: kind is defined and kind == "delete"