---
- name: Create ResourceQuota
  kubernetes.core.k8s:
    state: present
    kubeconfig: "~/.kube/config"
    context: "{{ k8s_namespace }}"
    definition: "{{ lookup('template', 'quota.j2') }}"
  register: quota_result

- name: Debug quota result
  debug:
    var: quota_result
