---
- name: Ensure the kubeconfig directory exists
  delegate_to: localhost
  ansible.builtin.file:
    path: ~/.kube
    state: directory
    mode: "0700"

- name: Create kubeconfig file from template
  delegate_to: localhost
  ansible.builtin.template:
    src: kubeconfig.j2
    dest: ~/.kube/config
    mode: "0600"

- name: Set KUBECONFIG environment variable
  delegate_to: localhost
  ansible.builtin.lineinfile:
    path: ~/.bashrc
    line: "export KUBECONFIG=~/.kube/config"
    create: yes
